- name: validate dns records
  debug: msg="Please confirm A record {{ item.name }} - {{ item.lookup }}"
  loop:
    - name: bootstrap
      lookup: "{{ lookup('dig', 'bootstrap.' + ocp4_cluster_name + '.' + domain + '.', 'flat=0', wantlist=True) }}"
    - name: etcd-0
      lookup: "{{ lookup('dig', 'etcd-0.' + ocp4_cluster_name + '.' + domain + '.', 'flat=0', wantlist=True) }}"
    - name: etcd-1
      lookup: "{{ lookup('dig', 'etcd-1.' + ocp4_cluster_name + '.' + domain + '.', 'flat=0', wantlist=True) }}"
    - name: etcd-2
      lookup: "{{ lookup('dig', 'etcd-2.' + ocp4_cluster_name + '.' + domain + '.', 'flat=0', wantlist=True) }}"
    - name: "*.apps"
      lookup: "{{ lookup('dig', 'test.apps.' + ocp4_cluster_name + '.' + domain + '.', 'flat=0', wantlist=True) }}"

- name: validate CNAME record for api-int.{{ ocp4_cluster_name }}
  debug: msg="Please confirm CNAME record {{ item.name }} - {{ item.lookup }}"
  loop:
    - name: api
      lookup: "{{ lookup('dig', 'api.' + ocp4_cluster_name + '.' + domain + '.', 'qtype=CNAME', 'flat=0', wantlist=True) }}"
    - name: api-int
      lookup: "{{ lookup('dig', 'api-int.' + ocp4_cluster_name + '.' + domain + '.', 'qtype=CNAME', 'flat=0', wantlist=True) }}"

- name: validate SRV dns records
  debug: msg="SRV record {{ item }}"
  with_items: "{{ lookup('dig', '_etcd-server-ssl._tcp.' + ocp4_cluster_name + '.' + domain + '.', 'qtype=SRV', 'flat=0', wantlist=True) }}"

- name: pause to verify DNS records. If DNS is not right, OpenShift will not deploy
  pause:

#- name: make cluster directory

#- name: create ocp4 install-config file
#openshift-install create install-config --dir=ocp

#- name: add ssh pub key to install config

#- name: add pull secret to install config

#- name: copy install-config.yaml into cluster director

#- name: create ocp4 manifests
#./openshift-install create manifests --dir=ocp/

#- name: modify cluster scheduler manifest for baremetal install
#vi ocp/manifests/cluster-scheduler-02-config.yml

#- name: create ocp4 ignition configs
#./openshift-install create ignition-configs --dir=ocp/

#- name: copy ignition configs to web server
#scp ocp/*.ign admin@10.99.99.11:/volume1/web/ocp42/ign/
